PANEL_HEIGHT = 60

PANEL_BUTTON_WIDTH = PANEL_HEIGHT - 10
PANEL_BUTTON_HEIGHT = PANEL_HEIGHT - 10

PANEL_WIDTH = PANEL_BUTTON_WIDTH + 10

BUILD_BUTTON_IMG = "Images/Buttons/Panel/build.png"

IGLOO_BUTTON_IMG = "Images/Buttons/Panel/Build/igloo.png"